# Override de producción
# Uso: docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d
services:
  backend:
    build: null
    image: localhost:5000/certvault-backend:${IMAGE_TAG}

  frontend:
    build: null
    image: localhost:5000/certvault-frontend:${IMAGE_TAG}