# Configuración de eventos generales para el servidor Nginx
events {
    # Límite de conexiones simultáneas por proceso de trabajo
    worker_connections 1024;
}

http {
    # Mapeo de tipos MIME y tipo por defecto
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # Ocultar la versión de Nginx en los encabezados por razones de seguridad
    server_tokens off;
    # Permitir subida de archivos grandes (máximo 100 Megabytes)
    client_max_body_size 100M;

    # Bloque de servidor para HTTP (puerto 80) - Redirige todo a HTTPS en el puerto 8080
    server {
        listen 80 default_server;
        server_name _;
        
        # Redirección permanente (301) forzando el esquema HTTPS en el puerto 8080
        location / {
            return 301 https://$host:8080$request_uri;
        }
    }

    # Bloque de servidor para HTTPS (puerto 443 interno) con terminación SSL
    server {
        listen 443 ssl default_server;
        server_name _;

        # Certificados SSL reales mapeados desde el volumen de Docker
        ssl_certificate /etc/nginx/certs/certvault-fullchain.pem;
        ssl_certificate_key /etc/nginx/certs/certvault.key;

        # Protocolos seguros de TLS admitidos
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_prefer_server_ciphers on;
        ssl_ciphers HIGH:!aNULL:!MD5;

        # Optimización de sesiones SSL para mejorar el rendimiento de reconexión
        ssl_session_cache shared:SSL:10m;
        ssl_session_timeout 1d;
        ssl_session_tickets off;

        # Enrutamiento de peticiones hacia el contenedor frontend (Angular)
        location / {
            # Resolvedor DNS interno de Docker para la resolución dinámica de nombres de contenedores
            resolver 127.0.0.11 valid=30s;
            # Variable para evadir el chequeo estático de host de Nginx en tiempo de inicio (evita caídas si el frontend no está listo)
            set $upstream_frontend http://certvault-frontend:80;

            proxy_pass $upstream_frontend;
            proxy_http_version 1.1;
            
            # Cabeceras requeridas para conservar los metadatos de la petición original
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            # Propaga el esquema original (https) que procesó este proxy
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
