# Configuración de eventos generales para el servidor Nginx
events {
    # Define el límite de conexiones simultáneas por proceso de trabajo
    worker_connections 1024;
}

http {
    # Mapeo de tipos MIME para garantizar la correcta interpretación de archivos estáticos
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # Ocultar la versión de Nginx en los encabezados de respuesta por razones de seguridad
    server_tokens off;
    # Limitar el tamaño máximo de carga permitido para prevenir ataques de denegación de servicio (DoS)
    client_max_body_size 100M;

    # Bloque de servidor para interceptar el tráfico HTTP (puerto 80) y forzar la redirección a HTTPS
    server {
        listen 80;
        # Hosts autorizados para esta directiva
        server_name localhost certvault.netics.corp 10.0.100.14;
        
        # Redirección permanente (301) hacia el mismo host y URI usando el esquema seguro HTTPS
        location / {
            return 301 https://$host$request_uri;
        }
    }

    # Bloque de servidor principal para el tráfico HTTPS (puerto 443) con terminación SSL
    server {
        listen 443 ssl;
        server_name localhost certvault.netics.corp 10.0.100.14;

        # Configuración de las rutas de certificados SSL montados en el volumen del contenedor
        ssl_certificate /etc/nginx/certs/ssl-cert-snakeoil.pem;
        ssl_certificate_key /etc/nginx/certs/ssl-cert-snakeoil.key;

        # Protocolos seguros de TLS admitidos, desactivando versiones antiguas y vulnerables (SSLv3, TLS 1.0, 1.1)
        ssl_protocols TLSv1.2 TLSv1.3;
        # Forzar el uso de cifrados configurados en el servidor sobre los del cliente
        ssl_prefer_server_ciphers on;
        # Conjunto de algoritmos de cifrado seguros y recomendados
        ssl_ciphers HIGH:!aNULL:!MD5;

        # Enrutamiento de las peticiones hacia el contenedor del Frontend (puerto 80 interno)
        location / {
            # Se utiliza el nombre del servicio definido en docker-compose.yml
            proxy_pass http://frontend:80;
            proxy_http_version 1.1;
            
            # Encabezados HTTP requeridos para transmitir la información del cliente original al backend
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
