name: Deploy automático a producción

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Install backend
        working-directory: /home/cdc/certvault/backend
        run: |
          npm install

      - name: Build backend
        working-directory: /home/cdc/certvault/backend
        run: |
          npm run build

      - name: Restart backend service
        run: pm2 restart certiapp

      - name: Install frontend
        working-directory: /home/cdc/certvault/certif-app
        run: |
          npm install

      - name: Build frontend
        working-directory: /home/cdc/certvault/certif-app
        run: |
          npm run build
